#!/usr/bin/env bash

# This script cleans up the backend for a stack when it is deleted.

echo "INFO: Cleanup environment state..."
ENV0_ENVIRONMENT_NAME_NORMALIZED=${ENV0_ENVIRONMENT_NAME// /_}
ENV0_ENVIRONMENT_NAME_NORMALIZED=${ENV0_ENVIRONMENT_NAME_NORMALIZED//[^a-zA-Z0-9-_]/}
ENV0_ENVIRONMENT_NAME_NORMALIZED=${ENV0_ENVIRONMENT_NAME_NORMALIZED,,}

BACKEND_S3_PREFIX="${PRODUCT_GROUP_STUB,,}/${WORKLOAD_ENVIRONMENT,,}/${ENV0_ENVIRONMENT_NAME_NORMALIZED}"

echo "INFO: Deleting s3://${BACKEND_S3_BUCKET}/${BACKEND_S3_PREFIX}..."
aws s3 rm --recursive "s3://${BACKEND_S3_BUCKET}/${BACKEND_S3_PREFIX}"
