global:
  enabled: true
server:
  standalone:
    enabled: false
  ingress:
    enabled: true
  ha:
    enabled: true
    replicas: 2
    config: |
      ui = true
      listener "tcp" {
        tls_disable = 1
        address = "[::]:8200"
        cluster_address = "[::]:8201"
      }
  volumes:
    - name: userconfig-vault-storage-config
      secret:
        defaultMode: "420"
        secretName: vault-storage-config
  volumeMounts:
    - name: userconfig-vault-storage-config
      mountPath: /vault/userconfig/vault-storage-config
      readOnly: true
  extraArgs: "-config=/vault/userconfig/vault-storage-config/config.hcl"

injector:
  enabled: false
ui:
  enabled: true
  serviceType: LoadBalancer
