AWSTemplateFormatVersion: '2010-09-09'
Resources:
  WebsiteBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Join ['', ['website-bucket-cf-', !Select [2, !Split ['/', !Ref AWS::StackId]]]]
      AccessControl: 'PublicRead'
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html
  WebsiteBucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref WebsiteBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: Allow-Public-Access-To-Bucket
            Effect: Allow
            Principal:
              AWS: '*'
            Action:
              - s3:GetObject
            Resource:
              - !Join ['', ['arn:aws:s3:::', !Ref WebsiteBucket, '/*']]
Outputs:
  BucketName:
    Value: !Ref WebsiteBucket
    Description: 'The name of the S3 bucket'
  BucketUrl:
    Value: !GetAtt WebsiteBucket.WebsiteURL
    Description: 'URL of the S3 bucket'
