apiVersion: v1
kind: Namespace
metadata:
  name: squid-proxy
  labels:
    app: squid

---
# Configuration for Squid-proxy
# This config is VERY permissive - all traffic can go through the proxy transparently
# Missing - user/pass authentication, SSL "bumping" (w/ self signed cert)
kind: ConfigMap
apiVersion: v1
metadata:
  name: proxy-configmap
  namespace: squid-proxy
data:
  squid.conf: |
    http_port 3128
        
    acl SSL_ports port 443
    acl CONNECT method CONNECT
        
    # allow all requests    
    http_access allow all
    coredump_dir /var/spool/squid

---
# Deployment for the proxy itself
apiVersion: apps/v1
kind: Deployment
metadata:
  name: squid
  namespace: squid-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: squid
  template:
    metadata:
      labels:
        app: squid
    spec:
      volumes:
        - name: proxy-config
          configMap:
            name: proxy-configmap
      containers:
        - name: squid
          image: sameersbn/squid:3.5.27-2
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: proxy-config
              mountPath: /etc/squid
              readOnly: true
