version: 1

deploy:
  steps:
    setupVariables:
      after:
        - awsv2 eks --region=${ENV0_CLUSTER_REGION:-us-east-1} update-kubeconfig --name ${ENV0_CLUSTER_NAME:-kushield}
        - "sed -i 's/command: aws/command: awsv2/g' ~/.kube/config"
        - cat /home/node/.kube/config

destroy:
  steps:
    setupVariables:
      after:
        - awsv2 eks --region=${ENV0_CLUSTER_REGION:-us-east-1} update-kubeconfig --name ${ENV0_CLUSTER_NAME:-kushield}
        - "sed -i 's/command: aws/command: awsv2/g' ~/.kube/config"
        - cat /home/node/.kube/config
