version: 1

deploy:
  steps:
    setupVariables:
      after: &login-k8s
        - echo 'ma'
        - echo 'luz'
        - mkdir -p ~/.kube
        - echo $NAMESPACE
        - kubectl config set-context aws --namespace $NAMESPACE
        - kubectl get namespaces

destroy:
  steps:
    setupVariables:
      after: *login-k8s
