version: 1

deploy:
  steps:
    setupVariables:
      after: &set-namespace-name
        - echo "$(sed 's/!!!NAMESPACE!!!/'"$NAMESPACE"'/g' namespace.yaml)" > namespace.yaml;
        - cat namespace.yaml

destroy:
  steps:
    setupVariables:
      after: *set-namespace-name
