version: 1

deploy:
  steps:
    setupVariables:
      after: &login-k8s
        - mkdir -p ~/.kube
        - echo $KUBE_CONFIG > ~/.kube/config
        - kubectl config set-context aws --namespace pr-ns;
        - echo "$(sed 's/!!!NAMESPACE!!!/'pr-ns'/g' namespace.yaml)" > namespace.yaml;
        - cat namespace.yaml
        - echo "---------" 
        - kubectl get namespaces
        - echo "---------" 
        - kustomize version

destroy:
  steps:
    setupVariables:
      after: *login-k8s
