version: 1

deploy:
  steps:
    setupVariables:
      after: &login-k8s
        - mkdir -p ~/.kube
        - echo $KUBE_CONFIG > ~/.kube/config
        - kubectl config set-context aws --namespace $NSAMESPACE;
        - echo "$(sed 's/!!!NAMESPACE!!!/'$NAMESPACE'/g' namespace.yaml)" > namespace.yaml;
        - cat namespace.yaml
        - echo "---------" 
        - kubectl version
        - echo "---------" 
        - kubectl get namespaces
        - echo "---------" 
        - kubectl describe namespace sagi-cia-k8s
        - echo "---------" 
        - kustomize version

destroy:
  steps:
    setupVariables:
      after: *login-k8s
