version: 1

deploy:
  steps:
    setupVariables:
      after: &login-k8s
        - echo 'ma'
        - echo 'luz'
        - aws eks --region=us-east-1 update-kubeconfig --name kushield --alias kushield
        - mkdir -p ~/.kube
        - kubectl get namespaces
        - echo $NAMESPACE
        - kubectl config set-context aws --namespace $NAMESPACE
        - kubectl get namespaces

destroy:
  steps:
    setupVariables:
      after: *login-k8s
