version: 1

deploy:
  steps:
    setupVariables:
      after: &login-k8s
        - aws eks --region=us-east-1 update-kubeconfig --name kushield --alias kushield
        - kubectl config get-contexts
        - kubectl config set-context kushield
destroy:
  steps:
    setupVariables:
      after: *login-k8s
