version: 1

deploy:
  steps:
    setupVariables:
      after: &login-k8s
        - echo 'ma'
        - echo 'luz'
        - mkdir -p ~/.kube
        - aws eks --region=us-east-1 update-kubeconfig --name kushield --alias kushield
        - echo $KUBE_CONFIG > ~/.kube/config
        - kubectl config set-context aws --namespace $NAMESPACE;
        - echo "$(sed 's/!!!NAMESPACE!!!/'"$NAMESPACE"'/g' namespace.yaml)" > namespace.yaml;
        - cat namespace.yaml

destroy:
  steps:
    setupVariables:
      after: *login-k8s
