apiVersion: v1
kind: Namespace
metadata:
  name: my-namespace
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-map-1
  namespace: my-namespace
data:
  key1: value1
  key2: value2
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-map-2
  namespace: my-namespace
data:
  key3: value3
  key4: value4